services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: stirling-pdf
    volumes:
      - ${STIRLING_CONFIG_FOLDER:-./configs}:/configs
      - ${STIRLING_LOGS_FOLDER:-./logs}:/logs
      - ${STIRLING_PIPELINE_FOLDER:-./pipeline}:/pipeline
      - ${TESSERACT_OCR_DATA_FOLDER:-/usr/share/tessdata}:/usr/share/tessdata
    environment:
      SECURITY_ENABLELOGIN: true
      SECURITY_INITIALLOGIN_USERNAME: admin
      SECURITY_INITIALLOGIN_PASSWORD: passwd
      LANGS: pt_BR
      SYSTEM_DEFAULTLOCALE: pt-BR
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${STIRLING_PDF_IP_ADDRESS}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}