services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: stirling-pdf
    volumes:
      - ${STIRLING_CONFIG_FOLDER:-./configs}:/configs
      - ${STIRLING_LOGS_FOLDER:-./logs}:/logs
      - ${STIRLING_PIPELINE_FOLDER:-./pipeline}:/pipeline
      - ${TESSERACT_OCR_DATA_FOLDER:-/usr/share/tessdata}:/usr/share/tessdata
    environment:
      SECURITY_ENABLELOGIN: true
      SECURITY_INITIALLOGIN_USERNAME: admin
      SECURITY_INITIALLOGIN_PASSWORD: passwd
      LANGS: pt_BR
      SYSTEM_DEFAULTLOCALE: pt-BR
      SYSTEM_MAXFILESIZE: 2000
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 2000MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 2000MB
      SYSTEM_GOOGLEVISIBILITY: false
      SYSTEM_ROOTURIPATH: /
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx4g"
      SYSTEM_ENABLEMOBILESCANNER: true
      SYSTEM_MOBILESCANNERSETTINGS_CONVERTTOPDF: true
      SYSTEM_MOBILESCANNERSETTINGS_IMAGERESOLUTION: full
      SYSTEM_MOBILESCANNERSETTINGS_PAGEFORMAT: A4
      SYSTEM_MOBILESCANNERSETTINGS_STRETCHTOFIT: false
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${STIRLING_PDF_IP_ADDRESS}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}